version: "3"
services:
  app:
    container_name: job-board-api
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://ec2-54-160-202-3.compute-1.amazonaws.com:5432/d29ec3ti33hr5p
      NODE_ENV: development
      PORT:
    ports:
      - ""
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    container_name: job-board-db
    image: postgres:9.6
    volumes:
      - $HOME/docker/volumes/job-board:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eczjhxppyvzedt
      POSTGRES_PASSWORD: 5efa0e60cf6bac3f06b1cc3cb1bb3f9098e35dd44eae5314889a2dba65bf36f6
      POSTGRES_DB: d29ec3ti33hr5p
